problem fixed
error C2440: 'initializing' : cannot convert from 'int' to
'tetgenmesh::interresult'

Conversion to enumeration type requires an explicit cast (static_cast,
C-style cast or function-style cast)